version: '3.8'
services:
  dms-server:
    container_name: 'dmsserver'
    build: ./dms-server
    restart: always
    # env_file: ./.env
    ports:
      - $RPC_SERVER_BASE_PORT:$RPC_SERVER_BASE_PORT
    environment:
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - RPC_SERVER_BASE_URL=$RPC_SERVER_BASE_URL
      - RPC_SERVER_BASE_PORT=$RPC_SERVER_BASE_PORT
    networks:
      - zitask
  gateway-server:
    container_name: 'gatewayserver'
    depends_on:
      - dms-server
    build: ./gateway-server
    restart: always
    # env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    environment:
      - RPC_SERVER_BASE_URL=dmsserver
      - RPC_SERVER_BASE_PORT=$RPC_SERVER_BASE_PORT
      - TOKEN_KEY=$TOKEN_KEY
    networks:
      - zitask
  dms-ui:
    container_name: 'dms-ui'
    depends_on:
      - gateway-server
    build: ./dms-ui
    restart: always
    # env_file: ./.env
    ports:
      - 80:80
    environment:
      - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
      - REACT_APP_API_PORT=$NODE_LOCAL_PORT
    networks:
      - zitask
networks:
  zitask:
    name: 'zitask'
    driver: 'bridge'