version: '3.8'
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  
  rpc-server:
    depends_on:
      - mongodb
    build: ./rpc-server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $RPC_SERVER_BASE_PORT:$RPC_SERVER_BASE_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - RPC_SERVER_BASE_URL=$RPC_SERVER_BASE_URL
      - RPC_SERVER_BASE_PORT=$RPC_SERVER_BASE_PORT
  rpc-gateway-server:
    depends_on:
      - rpc-server
    build: ./rpc-server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
     - RPC_SERVER_BASE_URL=$RPC_SERVER_BASE_URL
     - RPC_SERVER_BASE_PORT=$RPC_SERVER_BASE_PORT
     - TOKEN_KEY=$TOKEN_KEY
volumes: 
  db: